"""Add new columns to NGOs table

Revision ID: 9fafd7a3b276
Revises: f383d718af99
Create Date: 2025-03-01 19:01:27.035008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fafd7a3b276'
down_revision = 'f383d718af99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('official_name', sa.String(length=120), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('registration_number', sa.String(length=100), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('registration_date', sa.Date(), nullable=False, server_default='2025-01-01'))
        batch_op.add_column(sa.Column('ngo_type', sa.String(length=100), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('pan_number', sa.String(length=100), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('volunteer_details', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('darpan_cert_filename', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngos', schema=None) as batch_op:
        batch_op.drop_column('darpan_cert_filename')
        batch_op.drop_column('volunteer_details')
        batch_op.drop_column('website')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('address')
        batch_op.drop_column('pan_number')
        batch_op.drop_column('ngo_type')
        batch_op.drop_column('registration_date')
        batch_op.drop_column('registration_number')
        batch_op.drop_column('official_name')

    op.create_table('ngo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), nullable=False),
    sa.Column('official_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('ngo_summary', sa.TEXT(), nullable=False),
    sa.Column('logo', sa.VARCHAR(length=200), nullable=True),
    sa.Column('registration_number', sa.VARCHAR(length=100), nullable=False),
    sa.Column('registration_date', sa.DATE(), nullable=False),
    sa.Column('ngo_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('pan_number', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=False),
    sa.Column('contact_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('website', sa.VARCHAR(length=200), nullable=True),
    sa.Column('volunteer_details', sa.TEXT(), nullable=False),
    sa.Column('darpan_cert', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
